services:
  server:
    platform: linux/amd64
    image: softvence/diaz_backend_server:latest
    container_name: diaz_backend_api
    restart: always
    environment:
      NODE_ENV: 'production'
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/diaz_backend_db'

      JWT_SECRET: 'secret'
      JWT_EXPIRES_IN: 90d

      BASE_URL: 'https://lgcglobalcontractingltd.com/js'
      PORT: 5051

      MAIL_USER: 'arafatmannan2019@gmail.com'
      MAIL_PASS: 'eurp zvyi gnoy enag'

      REDIS_HOST: redis
      REDIS_PORT: 6379

      SUPER_ADMIN_EMAIL: 'sajib.softvence@gmail.com'
      SUPER_ADMIN_PASS: 'superadmin'

      STRIPE_SECRET_KEY: 'sk_test_51RlFNRQNJ9V9C9o5lWnJ0ZoVAb5almOirTaBvWZZOU74qXTIUaPeCRtnaHjGxts71VkVaK7tJA5JRjfjpKkeXJGo00dt24jNLx'
      STRIPE_WEBHOOK_SECRET: 'whsec_9Q1CdmnbOBvrajNmXM9n4U0Qz3OHYMUv'
    ports:
      - '5051:5051'
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        echo 'ğŸ Waiting for DB...';
        sleep 5;
        npx prisma migrate deploy;
        echo 'ğŸš€ Starting app...';
        pnpm start
      "
    volumes:
      - files-data:/app/uploads

  db:
    image: postgres
    container_name: diaz_backend_db
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diaz_backend_db
    volumes:
      - diaz_backend_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis
    container_name: diaz_backend_redis
    restart: always
    ports:
      - '6384:6379'

volumes:
  diaz_backend_data:
  files-data:
